### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [BUIQUOCDAT1281997/AVLTree#1]
1. Непонятно назначение методов `traversal`.
2. Отсутствуют `equals` и `hashCode`. Cм. документацию к `Set`.

**Comment by gagarski** [comment]
3. `AVLTreeIterator.remove` можно сделать эффективнее, если хранить стек узлов на пути к текущему.
4. Остутствует GUI-демонстрация, для отличной оценки она обязательна.

**Comment by BUIQUOCDAT1281997** [comment]
Здравствуйте. Я исправил . Прочитайте пожалуйста и дайте  мне замечания . Если в моей работе ошибки , я постараюсь исправить 
Спасибо Вам

**Comment by gagarski** [comment]
> Непонятно назначение методов traversal.

Всё ещё непонятно. Зачем они? 


По поводу итератора. Предлагаю оставить как есть. С учётом того, что в дереве при удалении могут происходить операции балансировки, поддерживать этот стек в актуальном состоянии довольно затруднительно.

**Comment by BUIQUOCDAT1281997** [comment]
это значит, что ничего переделывать не нужно?

**Comment by BUIQUOCDAT1281997** [comment]
> > Непонятно назначение методов traversal.
> 
 > Всё ещё непонятно. Зачем они?
>
По моему, будет лучше, если у нас есть Обход дерева :) Но если по Вашему он не нужно, то я уберу :)
